# -*- coding: utf-8 -*-
"""ML_Team25_miniproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5rW_S2eEHiIV23cxyKeoVdXFDkVJCPK

#ESSENTIAL IMPORTS
"""

!pip install --upgrade tensorflow

import tensorflow as tf
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Conv2DTranspose, Concatenate
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from google.colab import drive

print(f"TensorFlow version: {tf.__version__}")

"""# --- MOUNT GOOGLE DRIVE AND EXTRACT DATASET ---"""

drive.mount('/content/drive')

import zipfile
file_path = '/content/drive/MyDrive/png.zip'
extract_path = '/content/dataset'
os.makedirs(extract_path, exist_ok=True)

# Extract dataset
with zipfile.ZipFile(file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)
    print("Dataset extracted successfully!")

"""# --- DATA LOADING FUNCTION ---"""

def load_images_and_masks(image_dir, mask_dir, target_size=(256, 256)):
    """Load and preprocess satellite images and building masks"""
    images = []
    masks = []

    image_files = sorted([f for f in os.listdir(image_dir) if f.endswith('.png')])
    mask_files = sorted([f for f in os.listdir(mask_dir) if f.endswith('.png')])

    print(f"Loading: {len(image_files)} images from {os.path.basename(image_dir)}")

    for img_file, mask_file in zip(image_files, mask_files):
        # Load and preprocess image
        img_path = os.path.join(image_dir, img_file)
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, target_size)
        img = img.astype(np.float32) / 255.0

        # Load and preprocess mask
        mask_path = os.path.join(mask_dir, mask_file)
        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
        mask = cv2.resize(mask, target_size)
        mask = (mask > 127).astype(np.float32)  # Binarize mask

        images.append(img)
        masks.append(mask)

    return np.array(images), np.array(masks)

"""# --- LOAD ALL DATASETS ---"""

dataset_path = '/content/dataset'

train_images, train_masks = load_images_and_masks(
    os.path.join(dataset_path, 'train'),
    os.path.join(dataset_path, 'train_labels')
)

val_images, val_masks = load_images_and_masks(
    os.path.join(dataset_path, 'val'),
    os.path.join(dataset_path, 'val_labels')
)

test_images, test_masks = load_images_and_masks(
    os.path.join(dataset_path, 'test'),
    os.path.join(dataset_path, 'test_labels')
)

print(f"\nDataset Shapes:")
print(f"Train: {train_images.shape}")
print(f"Val:   {val_images.shape}")
print(f"Test:  {test_images.shape}")

"""As the dataset is image and there is storage issue, we are going forward with small dataset.

# --- U-NET MODEL ARCHITECTURE ---
"""

def build_unet(input_size=(256, 256, 3)):
    """U-Net architecture for semantic segmentation"""
    inputs = Input(input_size)

    # Encoder (Contracting Path)
    # Block 1
    c1 = Conv2D(32, (3, 3), activation='relu', padding='same')(inputs)
    c1 = Conv2D(32, (3, 3), activation='relu', padding='same')(c1)
    p1 = MaxPooling2D((2, 2))(c1)

    # Block 2
    c2 = Conv2D(64, (3, 3), activation='relu', padding='same')(p1)
    c2 = Conv2D(64, (3, 3), activation='relu', padding='same')(c2)
    p2 = MaxPooling2D((2, 2))(c2)

    # Bottleneck
    c3 = Conv2D(128, (3, 3), activation='relu', padding='same')(p2)
    c3 = Conv2D(128, (3, 3), activation='relu', padding='same')(c3)

    # Decoder (Expanding Path)
    # Block 4
    u4 = Conv2DTranspose(64, (2, 2), strides=(2, 2), padding='same')(c3)
    u4 = Concatenate()([u4, c2])
    c4 = Conv2D(64, (3, 3), activation='relu', padding='same')(u4)
    c4 = Conv2D(64, (3, 3), activation='relu', padding='same')(c4)

    # Block 5
    u5 = Conv2DTranspose(32, (2, 2), strides=(2, 2), padding='same')(c4)
    u5 = Concatenate()([u5, c1])
    c5 = Conv2D(32, (3, 3), activation='relu', padding='same')(u5)
    c5 = Conv2D(32, (3, 3), activation='relu', padding='same')(c5)

    # Output layer
    outputs = Conv2D(1, (1, 1), activation='sigmoid')(c5)

    model = Model(inputs=[inputs], outputs=[outputs])
    return model

"""# --- CREATE AND COMPILE MODEL ---"""

model = build_unet()
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

print("Model compiled successfully!")
model.summary()

"""# --- TRAINING THE MODEL ---"""

print("Starting training...")
history = model.fit(
    train_images, train_masks,
    batch_size=8,
    epochs=16,
    verbose=1,
    shuffle=True,
    validation_data=(val_images, val_masks)
)

print("Training completed!")

"""# --- EVALUATION METRICS ---"""

def calculate_iou(y_true, y_pred):
    """Calculate Intersection over Union metric"""
    y_pred_binary = (y_pred > 0.5).astype(np.float32)
    intersection = np.sum(y_true * y_pred_binary)
    union = np.sum(y_true) + np.sum(y_pred_binary) - intersection
    return intersection / (union + 1e-7)

"""# Predict on test set"""

test_predictions = model.predict(test_images, verbose=0)

"""# Calculate metrics"""

test_accuracy = np.mean((test_predictions.squeeze() > 0.5).astype(np.float32) == test_masks)
test_iou = calculate_iou(test_masks, test_predictions.squeeze())

"""# --- FINAL RESULTS ---"""

print("\n" + "="*50)
print("FINAL MODEL PERFORMANCE")
print("="*50)
print(f"Training Accuracy:   {train_accuracy:.2%}")
print(f"Test Accuracy:       {test_accuracy:.2%}")
print(f"Test IoU:           {test_iou:.2%}")
print("="*50)

"""# --- VISUALIZE RESULTS ---"""

def visualize_predictions(num_samples=3):
    """Visualize model predictions vs ground truth"""
    fig, axes = plt.subplots(num_samples, 3, figsize=(12, 4*num_samples))

    for i in range(num_samples):
        # Input image
        axes[i, 0].imshow(test_images[i])
        axes[i, 0].set_title(f'Input Image {i+1}')
        axes[i, 0].axis('off')

        # True mask
        axes[i, 1].imshow(test_masks[i], cmap='gray')
        axes[i, 1].set_title('True Buildings')
        axes[i, 1].axis('off')

        # Predicted mask
        pred_binary = (test_predictions[i].squeeze() > 0.5).astype(np.float32)
        axes[i, 2].imshow(pred_binary, cmap='gray')
        axes[i, 2].set_title('Predicted Buildings')
        axes[i, 2].axis('off')

    plt.tight_layout()
    plt.show()

visualize_predictions(10)

"""# --- SAVE MODEL ---"""

model.save('/content/building_segmentation_model.h5')
print("Model saved as '/content/building_segmentation_model.h5'")